root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
full_bin = "./tmp/server"
include_ext = ["go", "yaml", "yml"]
exclude_dir = ["tmp", "vendor", "charts"]
delay = 300
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true