services:
  claim-controller:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: ghcr.io/ia-generative/claim-controller:dev
    mem_limit: 2g
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./:/workspace
      # Mount the values file directly to the expected path in the container
      - ./values/values.yaml:/values/values.yaml:ro
      # Mount kubeconfig for in-cluster testing (optional, can be removed if not needed)
      - ${HOME}/.kube:/home/nonroot/.kube:ro
    environment:
      # This environment variable is used by the controller to locate the values file and not fallback to configmap mode
      VALUES_PATH: /values/values.yaml
      KUBECONFIG: /home/nonroot/.kube/config
      PRE_PROVISION_CLAIMS_COUNT: 2 # Example value, can be overridden by the values file