services:
  claim-controller:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: ghcr.io/ia-generative/claim-controller:dev
    mem_limit: 2g
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./:/workspace
      - ./templates/values.yaml:/values/values.yaml:ro
      - ${HOME}/.kube:/home/nonroot/.kube:ro
    environment:
      VALUES_PATH: /values/values.yaml
      KUBECONFIG: /home/nonroot/.kube/config