apiVersion: apps/v1
kind: Deployment
metadata:
  name: claim-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claim-controller
  template:
    metadata:
      labels:
        app: claim-controller
    spec:
      serviceAccountName: claim-controller
      containers:
        - name: manager
          image: ghcr.io/nonot/claim-controller:latest
          imagePullPolicy: IfNotPresent
          args:
            - --namespace=default
            - --values-path=/app/config/template/values.yaml
            - --max-ttl=10m
            - --api-addr=:8080
            - --metrics-addr=:8081
          ports:
            - name: api
              containerPort: 8080
            - name: metrics
              containerPort: 8081