{{- $ns := default .Release.Namespace .Values.namespace -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "claim-controller.fullname" . }}-template
  namespace: {{ $ns }}
data:
  resources.yaml: |
{{ .Values.template.file | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "claim-controller.fullname" . }}-template-values
  namespace: {{ $ns }}
data:
  values.yaml: |
{{ toYaml .Values.templateValues | indent 4 }}