{{- $ns := default .Release.Namespace .Values.namespace -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "claim-controller.fullname" . }}
  namespace: {{ $ns }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "claim-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "claim-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "claim-controller.serviceAccountName" . }}
      containers:
        - name: manager
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.api.addr }}
            - name: API_ADDR
              value: {{ .Values.api.addr | quote }}
            {{- end }}
            {{- if .Values.metrics.addr }}
            - name: METRICS_ADDR
              value: {{ .Values.metrics.addr | quote }}
            {{- end }}
            {{- if .Values.defaultTTL }}
            - name: DEFAULT_TTL
              value: {{ .Values.defaultTTL | quote }}
            {{- end }}
            {{- if .Values.maxTTL }}
            - name: MAX_TTL
              value: {{ .Values.maxTTL | quote }}
            {{- end }}
            {{- if .Values.reconcileInterval }}
            - name: RECONCILE_INTERVAL
              value: {{ .Values.reconcileInterval | quote }}
            {{- end }}
          ports:
            - name: api
              containerPort: 8080
            - name: metrics
              containerPort: 8081
            - name: probe
              containerPort: 8082
          resources:
{{ toYaml .Values.resources | indent 12 }}
