{{- $ns := default .Release.Namespace .Values.namespace -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "claim-controller.fullname" . }}
  namespace: {{ $ns }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "claim-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "claim-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "claim-controller.serviceAccountName" . }}
      containers:
        - name: manager
          image: {{ .Values.image.repository }}:{{ default .Values.image.tag .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VALUES_CONFIGMAP_NAME
              value: {{ include "claim-controller.fullname" . }}-values
            - name: VALUES_CONFIGMAP_KEY
              value: values.yaml
          ports:
            - name: api
              containerPort: 8080
            - name: metrics
              containerPort: 8081
            - name: probe
              containerPort: 8082
          resources:
{{ toYaml .Values.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "claim-controller.fullname" . }}
  namespace: {{ $ns }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "claim-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: api
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
{{- if .Values.service.externalName.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-external" (include "claim-controller.fullname" .)) .Values.service.externalName.name }}
  namespace: {{ $ns }}
spec:
  type: ExternalName
  externalName: {{ include "claim-controller.fullname" . }}.{{ $ns }}.svc.cluster.local
{{- end }}