{{- $ns := default .Release.Namespace .Values.namespace -}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "claim-controller.serviceAccountName" . }}
  namespace: {{ $ns }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "claim-controller.fullname" . }}
  namespace: {{ $ns }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "claim-controller.fullname" . }}
  namespace: {{ $ns }}
subjects:
  - kind: ServiceAccount
    name: {{ include "claim-controller.serviceAccountName" . }}
    namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "claim-controller.fullname" . }}