apiVersion: v1
kind: Service
metadata:
  name: {{ include "claim-controller.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "claim-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: api
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics